language: go

go:
  - master
stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        - go mod vendor
        - go get -u golang.org/x/lint/golint
        - golint -set_exit_status
        - go vet -v
    - stage: build
      script:
        - go build -mod=vendor

matrix:
  allow_failures:
    - go: main
  fast_finish: true
